# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.resize(595, 267)
        self.main_form_layout = QtWidgets.QHBoxLayout()
        self.main_form_layout.setObjectName("main_form_layout")
        self.game_name_linedit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name_linedit.sizePolicy().hasHeightForWidth())
        self.game_name_linedit.setSizePolicy(sizePolicy)
        self.game_name_linedit.setObjectName("game_name_linedit")
        self.main_form_layout.addWidget(self.game_name_linedit)
        self.description_linedit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_linedit.sizePolicy().hasHeightForWidth())
        self.description_linedit.setSizePolicy(sizePolicy)
        self.description_linedit.setObjectName("description_linedit")
        self.main_form_layout.addWidget(self.description_linedit)
        self.path_linedit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_linedit.sizePolicy().hasHeightForWidth())
        self.path_linedit.setSizePolicy(sizePolicy)
        self.path_linedit.setObjectName("path_linedit")
        self.main_form_layout.addWidget(self.path_linedit)
        self.path_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_button.sizePolicy().hasHeightForWidth())
        self.path_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.path_button.setFont(font)
        self.path_button.setMouseTracking(False)
        self.path_button.setAcceptDrops(False)
        self.path_button.setObjectName("path_button")
        self.main_form_layout.addWidget(self.path_button)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.main_form_layout.addWidget(self.pushButton)

        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.path_button.setText(_translate("Form", "выбрать файл"))
        self.pushButton.setText(_translate("Form", "удалить"))
